-- liquibase formatted sql

-- changeset anton:5
ALTER TABLE warehouses ADD COLUMN created_by VARCHAR(50);
ALTER TABLE warehouses ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE warehouses ADD COLUMN last_modified_by VARCHAR(50);
ALTER TABLE warehouses ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE products ADD COLUMN created_by VARCHAR(50);
ALTER TABLE products ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE products ADD COLUMN last_modified_by VARCHAR(50);
ALTER TABLE products ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE supplies ADD COLUMN created_by VARCHAR(50);
ALTER TABLE supplies ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE supplies ADD COLUMN last_modified_by VARCHAR(50);
ALTER TABLE supplies ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE shipments ADD COLUMN created_by VARCHAR(50);
ALTER TABLE shipments ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE shipments ADD COLUMN last_modified_by VARCHAR(50);
ALTER TABLE shipments ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE stock_levels ADD COLUMN created_by VARCHAR(50);
ALTER TABLE stock_levels ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE stock_levels ADD COLUMN last_modified_by VARCHAR(50);
ALTER TABLE stock_levels ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;